### ISSUE TITLE
[repl] selectable command through history

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#104]
This is migration from REPL in the old implementation, but keeping the benefit from DrRacket's REPL would be good. Thus, rather than directly move the same code and overwrite `on-char`, better figure out how to put the function without too many code changes.

### TODO

- [x] up: previous expression(if any)
- [x] down: next expression(if any)
- [x] won't affect current editing, so up/down shouldn't work when the cursor is not located at the prompt position.

### Reference

- https://docs.racket-lang.org/tools/drracket_get_extend.html?q=drracket#%28def._%28%28lib._drracket%2Ftool-lib..rkt%29._drracket~3aget%2Fextend~3aextend-interactions-text%29%29
- https://docs.racket-lang.org/tools/drracket_get_extend.html?q=drracket#%28def._%28%28lib._drracket%2Ftool-lib..rkt%29._drracket~3aget%2Fextend~3aextend-interactions-canvas%29%29
